//! Free integer lattices and their sublattices.
//!
//! A [`Sublattice`] is a subgroup of `Z^n` given by a canonical basis. Because
//! the basis is the canonical Hermite normal form of any generating set, two
//! sublattices of the same ambient rank are equal exactly when their bases are
//! equal: presentation equality and mathematical equality coincide here, which
//! is not true of the generating sets they were built from.

use alloc::vec::Vec;

use num_integer::Integer;
use num_traits::Zero;

use crate::algebra::Z;
use crate::algebra::matrix::IntMatrix;
use crate::algebra::normal_form::{HermiteNormalForm, SmithNormalForm};
use crate::error::MatrixError;

/// A subgroup of the free abelian group `Z^n`, given by a canonical basis.
///
/// UMT layer: L1/L2, exact.
///
/// The basis columns are the canonical Hermite normal form of the generators,
/// so equality is both presentation equality and mathematical equality of the
/// subgroups.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Sublattice {
    ambient_rank: usize,
    basis: IntMatrix,
    pivots: Vec<(usize, usize)>,
}

impl Sublattice {
    /// Builds the sublattice generated by the columns of `generators`.
    ///
    /// # Errors
    ///
    /// Returns [`MatrixError::DimensionMismatch`] if the generator matrix does
    /// not have `ambient_rank` rows.
    pub fn from_generators(
        ambient_rank: usize,
        generators: &IntMatrix,
    ) -> Result<Self, MatrixError> {
        if generators.rows() != ambient_rank {
            return Err(MatrixError::DimensionMismatch {
                left: ambient_rank,
                right: generators.rows(),
            });
        }
        let hermite = HermiteNormalForm::column_of(generators);
        Ok(Self {
            ambient_rank,
            basis: hermite.basis(),
            pivots: hermite.pivots().to_vec(),
        })
    }

    /// The trivial subgroup `{0}`.
    #[must_use]
    pub fn trivial(ambient_rank: usize) -> Self {
        Self {
            ambient_rank,
            basis: IntMatrix::zeros(ambient_rank, 0),
            pivots: Vec::new(),
        }
    }

    /// The whole ambient lattice.
    #[must_use]
    pub fn full(ambient_rank: usize) -> Self {
        Self {
            ambient_rank,
            basis: IntMatrix::identity(ambient_rank),
            pivots: (0..ambient_rank).map(|index| (index, index)).collect(),
        }
    }

    /// The rank of the ambient lattice.
    #[must_use]
    pub fn ambient_rank(&self) -> usize {
        self.ambient_rank
    }

    /// The rank of this sublattice.
    #[must_use]
    pub fn rank(&self) -> usize {
        self.basis.cols()
    }

    /// The canonical basis, as columns in ambient coordinates.
    #[must_use]
    pub fn basis(&self) -> &IntMatrix {
        &self.basis
    }

    /// Whether this sublattice is the whole ambient lattice.
    ///
    /// Equal rank is not enough: `2Z` has the rank of `Z` without being `Z`.
    #[must_use]
    pub fn is_full(&self) -> bool {
        self.basis == IntMatrix::identity(self.ambient_rank)
    }

    /// Whether this sublattice is trivial.
    #[must_use]
    pub fn is_trivial(&self) -> bool {
        self.rank() == 0
    }

    /// Embeds intrinsic coordinates into the ambient lattice.
    ///
    /// # Errors
    ///
    /// Returns [`MatrixError::DimensionMismatch`] if the coordinate count
    /// differs from the rank.
    pub fn embed(&self, coordinates: &[Z]) -> Result<Vec<Z>, MatrixError> {
        self.basis.apply(coordinates)
    }

    /// The intrinsic coordinates of an ambient point, or `None` if the point
    /// is not in this sublattice.
    ///
    /// # Errors
    ///
    /// Returns [`MatrixError::DimensionMismatch`] if the point does not have
    /// `ambient_rank` entries.
    pub fn coordinates(&self, point: &[Z]) -> Result<Option<Vec<Z>>, MatrixError> {
        if point.len() != self.ambient_rank {
            return Err(MatrixError::DimensionMismatch {
                left: self.ambient_rank,
                right: point.len(),
            });
        }
        let mut residual: Vec<Z> = point.to_vec();
        let mut coordinates = Vec::with_capacity(self.rank());

        for (column, (row, _)) in self.pivots.iter().enumerate() {
            let pivot = self.basis.at(*row, column);
            let (quotient, remainder) = residual[*row].div_rem(pivot);
            if !remainder.is_zero() {
                return Ok(None);
            }
            for (target, entry) in residual.iter_mut().enumerate() {
                *entry -= self.basis.at(target, column) * &quotient;
            }
            coordinates.push(quotient);
        }

        if residual.iter().all(Zero::is_zero) {
            Ok(Some(coordinates))
        } else {
            Ok(None)
        }
    }

    /// The canonical representative of the coset `point + L`.
    ///
    /// Every coset has exactly one representative whose coordinate at each
    /// pivot row lies in `[0, pivot)`, so this decides coset equality: two
    /// points lie in the same coset exactly when their reductions are equal.
    /// It is also what keeps derived representatives small - an unreduced
    /// solution of a linear system can be enormous while representing the same
    /// coset.
    ///
    /// # Errors
    ///
    /// Returns [`MatrixError::DimensionMismatch`] if the point does not have
    /// `ambient_rank` entries.
    pub fn reduce(&self, point: &[Z]) -> Result<Vec<Z>, MatrixError> {
        if point.len() != self.ambient_rank {
            return Err(MatrixError::DimensionMismatch {
                left: self.ambient_rank,
                right: point.len(),
            });
        }
        let mut reduced = point.to_vec();
        for (column, (row, _)) in self.pivots.iter().enumerate() {
            let quotient = reduced[*row].div_floor(self.basis.at(*row, column));
            if quotient.is_zero() {
                continue;
            }
            for (target, entry) in reduced.iter_mut().enumerate() {
                *entry -= self.basis.at(target, column) * &quotient;
            }
        }
        Ok(reduced)
    }

    /// The canonical representative of the coset `point + L`, eliminating from
    /// the *last* coordinate downwards.
    ///
    /// Same guarantee as [`Sublattice::reduce`] - one representative per
    /// coset, deterministic - but with the coordinate order reversed, so the
    /// exponents of the later generators are the ones driven into
    /// `[0, pivot)`.
    ///
    /// For a prime basis this is usually the one wanted: the later generators
    /// are the arithmetically complex ones, so keeping *their* exponents small
    /// produces representatives a musician recognizes. Reducing the 12-EDO
    /// fifth class from the front yields a twenty-digit ratio; reducing it
    /// from the back yields `3/2`.
    ///
    /// # Errors
    ///
    /// Returns [`MatrixError::DimensionMismatch`] if the point does not have
    /// `ambient_rank` entries.
    pub fn reduce_reversed(&self, point: &[Z]) -> Result<Vec<Z>, MatrixError> {
        let reversed = Self::from_generators(self.ambient_rank, &self.basis.reverse_rows())?;
        let flipped: Vec<Z> = point.iter().rev().cloned().collect();
        let reduced = reversed.reduce(&flipped)?;
        Ok(reduced.into_iter().rev().collect())
    }

    /// Whether an ambient point lies in this sublattice.
    ///
    /// # Errors
    ///
    /// Returns [`MatrixError::DimensionMismatch`] if the point does not have
    /// `ambient_rank` entries.
    pub fn contains(&self, point: &[Z]) -> Result<bool, MatrixError> {
        Ok(self.coordinates(point)?.is_some())
    }

    /// Whether this sublattice is saturated in the ambient lattice.
    ///
    /// A sublattice `L <= Z^n` is saturated when `x in Z^n` and `n x in L` for
    /// some nonzero integer `n` together imply `x in L`; equivalently, when
    /// `Z^n / L` is torsion-free (UMT-3.2 section 1.5).
    #[must_use]
    pub fn is_saturated(&self) -> bool {
        SmithNormalForm::of(&self.basis).has_saturated_column_lattice()
    }

    /// The saturation of this sublattice.
    ///
    /// This is the smallest saturated sublattice containing it: the set of
    /// ambient points some nonzero multiple of which lies in this one. It is
    /// returned as a distinct value; nothing is mutated, so a caller can
    /// report the change as UMT-3.2 section 1.5 requires.
    #[must_use]
    pub fn saturation(&self) -> Self {
        let basis = SmithNormalForm::of(&self.basis).saturation_basis();
        Self::from_generators(self.ambient_rank, &basis)
            .expect("invariant: saturation basis has ambient_rank rows")
    }
}

#[cfg(test)]
mod tests {
    use super::Sublattice;
    use crate::algebra::Z;
    use crate::algebra::matrix::IntMatrix;
    use alloc::vec;

    fn z(values: &[i64]) -> alloc::vec::Vec<Z> {
        values.iter().map(|v| Z::from(*v)).collect()
    }

    #[test]
    fn generators_are_canonicalized() {
        let a = Sublattice::from_generators(2, &IntMatrix::from_rows([[2i64, 0], [0, 3]]).unwrap())
            .unwrap();
        let b = Sublattice::from_generators(
            2,
            &IntMatrix::from_rows([[2i64, 2, 4], [3, 6, 9]]).unwrap(),
        )
        .unwrap();
        assert_eq!(a.rank(), 2);
        assert_eq!(a, b, "the same lattice has one canonical basis");
    }

    #[test]
    fn membership_and_coordinates_round_trip() {
        // 2Z inside Z.
        let doubled =
            Sublattice::from_generators(1, &IntMatrix::from_rows([[2i64]]).unwrap()).unwrap();
        assert!(!doubled.is_full());
        assert!(doubled.contains(&z(&[4])).unwrap());
        assert!(!doubled.contains(&z(&[3])).unwrap());
        assert_eq!(doubled.coordinates(&z(&[6])).unwrap(), Some(z(&[3])));
        assert_eq!(doubled.coordinates(&z(&[-6])).unwrap(), Some(z(&[-3])));
        assert_eq!(doubled.coordinates(&z(&[1])).unwrap(), None);
        assert_eq!(doubled.embed(&z(&[3])).unwrap(), z(&[6]));
    }

    #[test]
    fn coordinates_in_higher_rank() {
        let lattice = Sublattice::from_generators(
            3,
            &IntMatrix::from_rows([[1i64, 0], [1, 2], [0, 4]]).unwrap(),
        )
        .unwrap();
        assert_eq!(lattice.rank(), 2);
        let point = lattice.embed(&z(&[3, -2])).unwrap();
        assert_eq!(lattice.coordinates(&point).unwrap(), Some(z(&[3, -2])));
        assert_eq!(lattice.coordinates(&z(&[0, 0, 1])).unwrap(), None);
    }

    #[test]
    fn dimension_mismatches_are_rejected() {
        let lattice = Sublattice::full(2);
        assert!(lattice.coordinates(&z(&[1])).is_err());
        assert!(Sublattice::from_generators(2, &IntMatrix::zeros(3, 1)).is_err());
    }

    #[test]
    fn trivial_and_full_extremes() {
        let trivial = Sublattice::trivial(3);
        assert!(trivial.is_trivial());
        assert!(!trivial.is_full());
        assert!(trivial.contains(&z(&[0, 0, 0])).unwrap());
        assert!(!trivial.contains(&z(&[0, 1, 0])).unwrap());
        assert_eq!(trivial.coordinates(&z(&[0, 0, 0])).unwrap(), Some(vec![]));
        assert!(trivial.is_saturated(), "the trivial subgroup is saturated");

        let full = Sublattice::full(3);
        assert!(full.is_full());
        assert!(full.contains(&z(&[5, -7, 11])).unwrap());
        assert!(full.is_saturated());
    }

    #[test]
    fn reduction_gives_canonical_coset_representatives() {
        let lattice =
            Sublattice::from_generators(2, &IntMatrix::from_rows([[3i64, 0], [0, 5]]).unwrap())
                .unwrap();

        // Same coset, same reduction.
        assert_eq!(lattice.reduce(&z(&[7, 12])).unwrap(), z(&[1, 2]));
        assert_eq!(lattice.reduce(&z(&[-2, -3])).unwrap(), z(&[1, 2]));
        assert_eq!(lattice.reduce(&z(&[1, 2])).unwrap(), z(&[1, 2]));

        // Different cosets, different reductions.
        assert_ne!(
            lattice.reduce(&z(&[1, 2])).unwrap(),
            lattice.reduce(&z(&[2, 2])).unwrap()
        );

        // Members of the lattice reduce to zero.
        assert_eq!(lattice.reduce(&z(&[6, -10])).unwrap(), z(&[0, 0]));

        // The difference is always in the lattice, and reduction is
        // idempotent.
        for point in [z(&[17, -23]), z(&[0, 1]), z(&[-100, 100])] {
            let reduced = lattice.reduce(&point).unwrap();
            let difference: alloc::vec::Vec<Z> =
                point.iter().zip(&reduced).map(|(a, b)| a - b).collect();
            assert!(lattice.contains(&difference).unwrap());
            assert_eq!(lattice.reduce(&reduced).unwrap(), reduced);
        }
    }

    #[test]
    fn reduction_in_a_rank_deficient_lattice_leaves_free_coordinates_alone() {
        // Only the first coordinate is constrained.
        let lattice =
            Sublattice::from_generators(2, &IntMatrix::from_rows([[4i64], [0]]).unwrap()).unwrap();
        assert_eq!(lattice.reduce(&z(&[9, 7])).unwrap(), z(&[1, 7]));
        assert_eq!(lattice.reduce(&z(&[-1, -7])).unwrap(), z(&[3, -7]));
    }

    #[test]
    fn saturation_of_a_multiple_of_a_primitive_vector() {
        // Twice the syntonic comma.
        let doubled =
            Sublattice::from_generators(3, &IntMatrix::from_rows([[-8i64], [8], [-2]]).unwrap())
                .unwrap();
        assert!(!doubled.is_saturated());

        let saturation = doubled.saturation();
        assert!(saturation.is_saturated());
        assert_eq!(saturation.rank(), 1);
        assert!(saturation.contains(&z(&[-4, 4, -1])).unwrap());
        assert!(saturation.contains(&z(&[-8, 8, -2])).unwrap());
        assert!(!doubled.contains(&z(&[-4, 4, -1])).unwrap());
        assert_eq!(
            saturation.saturation(),
            saturation,
            "saturation is idempotent"
        );
    }
}
