//! UMT-3.2 conformance fixtures (specification section 9.13).
//!
//! `docs/conformance.md` maps every fixture to its test and status. Fixtures
//! whose machinery is not implemented yet are absent from this file rather
//! than stubbed, because a skipped law must never look like a passing one
//! (prompt section 60, item 20).
//!
//! Tests named `*_partial` cover the part of a fixture that the implemented
//! layers can decide. The remaining obligations are listed in the docs table.

use std::sync::Arc;

use umt::algebra::QuotientGroup;
use umt::algebra::lattice::Sublattice;
use umt::error::{ComplexityError, TemperamentError};
use umt::pitch::{
    Cents, FrequencyHz, LogFrequency, Octaves, PitchOrigin, PitchPoint, PitchRealization,
    PitchRealizer, RegularTuning,
};
use umt::proportion::{
    Complexity, ComplexityProfile, LogWeightedL1, PositiveFinite, RealValuation, WeightedL1,
};
use umt::realization::optimization::OptimizationOutcome;
use umt::temperament::{
    AmbientLattice, EquivalenceDomain, HomomorphicSplit, KernelLattice, LinearSplit, OffsetPolicy,
    RepresentativePolicy, SaturationPolicy, SplitPolicy, StructuralLens, TemperamentMap,
    UnitEquivalence,
};
use umt::{Basis, IntMatrix, PatentVal, RoundingConvention, Z};

const NEAREST: RoundingConvention = RoundingConvention::NearestHalfAwayFromZero;

fn five_limit() -> Arc<Basis> {
    Basis::primes("umt:prime:2.3.5", &[2, 3, 5]).expect("valid prime basis")
}

/// F1 - kernel saturation versus surjectivity.
///
/// `V = [2] : Z -> Z` has trivial, hence saturated, kernel, while its image is
/// `2Z` and the mapping is not surjective. The two properties are independent,
/// and the gcd-of-minors condition that governs surjectivity says nothing
/// about the kernel (UMT-3.2 section 1.4.2).
#[test]
fn f01_kernel_saturation_versus_surjectivity() {
    let domain = Basis::primes("umt:prime:2", &[2]).unwrap();
    let ambient = AmbientLattice::new("umt:f01-ambient", 1);
    let map = TemperamentMap::from_rows(&domain, &ambient, [[2i64]]).unwrap();

    // Kernel is trivial and therefore saturated.
    assert_eq!(map.kernel().rank(), 0);
    assert!(map.kernel().is_saturated());
    assert!(!map.kills(&domain.monzo([1]).unwrap()).unwrap());

    // Image is 2Z: rank 1, but not the whole ambient lattice.
    assert_eq!(map.image().rank(), 1);
    assert!(!map.is_surjective());
    assert_eq!(
        map.image().basis(),
        &IntMatrix::from_rows([[2i64]]).unwrap()
    );
    assert_eq!(map.invariant_factors(), &[Z::from(2)]);

    let odd = ambient.element([1i64]).unwrap();
    assert!(!map.image().contains(&odd).unwrap());
}

/// F2 - unsaturated direct comma subgroup.
///
/// The subgroup generated by twice a primitive comma has 2-torsion in its
/// quotient. The direct-comma validator must report it; the map-derived-kernel
/// path must not have that validator applied to it, since such a kernel is
/// saturated as a theorem (UMT-3.2 sections 1.4.1 and 1.5).
#[test]
fn f02_unsaturated_direct_comma_subgroup() {
    let basis = five_limit();
    let doubled_comma = IntMatrix::from_rows([[-8i64], [8], [-2]]).unwrap();

    // Rejecting policy: reported as unsaturated, with the torsion order.
    assert_eq!(
        KernelLattice::from_direct_commas(&basis, &doubled_comma, SaturationPolicy::Reject)
            .unwrap_err(),
        TemperamentError::UnsaturatedCommaSubgroup {
            torsion_invariants: vec![Z::from(2)]
        }
    );

    // Saturating policy: replaced, and the change is reported.
    let (saturated, report) =
        KernelLattice::from_direct_commas(&basis, &doubled_comma, SaturationPolicy::Saturate)
            .unwrap();
    assert!(!report.was_saturated);
    assert_eq!(report.torsion_invariants, vec![Z::from(2)]);
    assert_eq!(report.rank, 1);
    assert!(saturated.is_saturated());
    // The comma itself is now in the subgroup; it was not before.
    let comma = basis.monzo([-4, 4, -1]).unwrap();
    assert!(saturated.contains(&comma).unwrap());
    let (unsaturated, _) =
        KernelLattice::from_direct_commas(&basis, &doubled_comma, SaturationPolicy::Saturate)
            .unwrap();
    assert!(
        unsaturated.is_saturated(),
        "the returned lattice is the saturation"
    );

    // The map-derived kernel of a mapping that tempers out the doubled comma
    // is the saturated one, and no saturation validation was applied to it.
    let ambient = AmbientLattice::new("umt:edo:12", 1);
    let map = TemperamentMap::from_rows(&basis, &ambient, [[12i64, 19, 28]]).unwrap();
    assert!(map.kernel().is_saturated());
    assert!(map.kernel().contains(&comma).unwrap());
}

/// F3 - 12-EDO quotient.
///
/// The syntonic and Pythagorean commas are both killed; the exact tempered
/// quotient `T = Lambda_B / K` is free of rank 1, that is, isomorphic to `Z`,
/// before octave equivalence; and after octave equivalence with the octave
/// mapped to 12 steps the pitch classes form `Z/12Z`.
#[test]
fn f03_twelve_edo_quotient() {
    let basis = five_limit();
    let ambient = AmbientLattice::new("umt:edo:12", 1);
    let map = TemperamentMap::from_rows(&basis, &ambient, [[12i64, 19, 28]]).unwrap();

    let syntonic = basis.monzo([-4, 4, -1]).unwrap();
    let pythagorean = basis.monzo([-19, 12, 0]).unwrap();
    assert!(map.kills(&syntonic).unwrap());
    assert!(map.kills(&pythagorean).unwrap());

    // The tempered quotient itself, built rather than inferred.
    let tempered = QuotientGroup::of(basis.rank(), map.kernel().sublattice()).unwrap();
    assert_eq!(
        tempered.to_string(),
        "Z",
        "T = Lambda_B / K is free of rank 1"
    );
    assert_eq!(tempered.free_rank(), 1);
    assert!(tempered.is_torsion_free());

    // And T is isomorphic to H, which here is all of Gamma.
    assert_eq!(map.image().rank(), tempered.free_rank());
    assert!(map.image().is_full(), "H = Gamma = Z");

    // Both commas generate the kernel between them.
    let kernel_from_commas = KernelLattice::of_map(
        &basis,
        &IntMatrix::from_rows([[-4i64, -19], [4, 12], [-1, 0]]).unwrap(),
    )
    .unwrap();
    assert_eq!(&kernel_from_commas, map.kernel());

    // After octave equivalence, pitch classes form Z/12Z.
    let octave = basis.monzo([1, 0, 0]).unwrap();
    assert_eq!(map.apply(&octave).unwrap().coordinates(), &[Z::from(12)]);
    let classes = UnitEquivalence::on_ambient(&map, &octave).unwrap();
    assert_eq!(classes.quotient().to_string(), "Z/12Z");
    assert_eq!(classes.class_count(), Some(Z::from(12)));
    assert_eq!(classes.domain(), EquivalenceDomain::Ambient);
}

/// F4 - 6-EDO image.
///
/// The ambient step lattice `Gamma = Z` and the mapped image `H = 2Z` are
/// separately represented, and detempering is defined only on `H`: an odd
/// ambient step cannot even be turned into a class to ask a policy about, so
/// there is no automatic L1 detempering for it.
#[test]
fn f04_6edo_image() {
    let basis = five_limit();
    let val = PatentVal::new(&basis, 6, NEAREST).unwrap();

    assert_eq!(
        val.entries(),
        &[Z::from(6), Z::from(10), Z::from(14)],
        "the usual 5-limit patent val for 6-EDO"
    );

    // Image is 2Z, a proper subgroup of the ambient Z.
    assert_eq!(val.image_generator(), Z::from(2));
    assert!(!val.is_surjective());
    assert_eq!(
        val.map().image().basis(),
        &IntMatrix::from_rows([[2i64]]).unwrap()
    );

    // Odd ambient steps exist but are not reached.
    for odd in [-5i64, -3, -1, 1, 3, 5, 7] {
        let step = Z::from(odd);
        assert!(!val.contains_ambient(&step), "step {odd} must not be in H");
        assert_eq!(
            val.image_coordinate(&step),
            Err(TemperamentError::NotInImage {
                coordinates: vec![Z::from(odd)]
            }),
            "step {odd} has no automatic L1 detempering"
        );
    }

    // Even steps are reached, and their intrinsic image coordinates differ
    // from their ambient coordinates.
    for even in [-4i64, -2, 0, 2, 4, 6] {
        let step = Z::from(even);
        assert!(val.contains_ambient(&step));
        let coordinate = val.image_coordinate(&step).unwrap();
        assert_eq!(coordinate, Z::from(even / 2));
        assert_eq!(val.embed_image(&coordinate).unwrap(), step);
    }

    // Detempering is defined on H, and only on H. A representative policy
    // takes an `ImageElem`, which an odd ambient step cannot produce, so the
    // failure happens before any policy is consulted.
    let map = val.map();
    let split = LinearSplit::of(map).unwrap();
    for even in [-4i64, -2, 0, 2, 4, 6] {
        let class = map
            .image()
            .from_ambient(&map.ambient().element([even]).unwrap())
            .unwrap();
        let lift = split.split(&class).unwrap();
        assert_eq!(map.apply(&lift).unwrap().coordinates(), &[Z::from(even)]);
    }
    for odd in [-3i64, -1, 1, 3] {
        assert!(
            map.image()
                .from_ambient(&map.ambient().element([odd]).unwrap())
                .is_err(),
            "an odd step is not a class, so no lift can be requested for it"
        );
    }
}

/// F5 - height with a generator below 1.
///
/// A generic complexity must use explicitly declared positive weights. A
/// generator whose valuation is below 1 has a negative logarithm, and an
/// implementation that blindly used `log2 b_i` as a norm weight would produce
/// a function that is not a norm at all.
#[test]
fn f05_height_with_a_generator_below_one() {
    let basis = Basis::builder("umt:symbolic:sub-unit")
        .symbolic_real_generator(
            "half",
            RealValuation::new(PositiveFinite::new(0.5).unwrap()),
        )
        .symbolic_real_generator(
            "three",
            RealValuation::new(PositiveFinite::new(3.0).unwrap()),
        )
        .symbolic_real_generator(
            "seven",
            RealValuation::new(PositiveFinite::new(7.0).unwrap()),
        )
        .build()
        .unwrap();

    // Deriving weights from logarithms is refused, with the offending
    // generator and weight reported.
    match LogWeightedL1::from_log2_valuations(&basis) {
        Err(ComplexityError::NonPositiveWeight { index, weight }) => {
            assert_eq!(index, 0);
            assert!(weight < 0.0);
        }
        other => panic!("expected rejection of a negative log weight, got {other:?}"),
    }

    // Tenney height is not even applicable: this is not a prime basis.
    assert_eq!(
        LogWeightedL1::tenney(&basis).unwrap_err(),
        ComplexityError::NotPrimeBasis
    );

    // Explicit positive weights are the supported route, and they give a norm.
    let weights = [1.0f64, 1.585, 2.807].map(|w| PositiveFinite::new(w).unwrap());
    let norm = LogWeightedL1::new(&basis, weights).unwrap();
    assert_eq!(norm.profile(), ComplexityProfile::LatticeNorm);
    for exponents in [[1i64, 0, 0], [-3, 2, 1], [0, 0, -4]] {
        let monzo = basis.monzo(exponents).unwrap();
        assert!(norm.value_f64(&monzo).unwrap() > 0.0);
    }
    assert_eq!(norm.value_f64(&basis.zero()).unwrap(), 0.0);
}

/// F34 - group length versus lattice norm.
///
/// `g(m) = sqrt(h1(m))` satisfies the separating group-length laws but fails
/// integer homogeneity, so it must be declared a `group_length` and must not
/// be advertised as a `lattice_norm`.
#[test]
fn f34_group_length_versus_lattice_norm() {
    struct SquareRoot(WeightedL1);

    impl Complexity for SquareRoot {
        fn basis(&self) -> &Arc<Basis> {
            self.0.basis()
        }

        fn profile(&self) -> ComplexityProfile {
            ComplexityProfile::GroupLength { separating: true }
        }

        fn value_f64(&self, monzo: &umt::Monzo) -> Result<f64, ComplexityError> {
            Ok(self.0.value_f64(monzo)?.sqrt())
        }
    }

    let basis = five_limit();
    let base = WeightedL1::uniform(&basis);
    let root = SquareRoot(base);

    // Declared as a group length, and a separating one.
    assert_eq!(
        root.profile(),
        ComplexityProfile::GroupLength { separating: true }
    );
    assert!(!root.profile().claims_homogeneity());
    assert!(root.profile().claims_subadditivity());
    assert_ne!(root.profile(), ComplexityProfile::LatticeNorm);

    let m = basis.monzo([-4, 4, -1]).unwrap();
    let n = basis.monzo([3, -1, 2]).unwrap();

    // h(0) = 0, symmetry, subadditivity, separation.
    assert_eq!(root.value_f64(&basis.zero()).unwrap(), 0.0);
    assert_eq!(root.value_f64(&m).unwrap(), root.value_f64(&-&m).unwrap());
    assert!(
        root.value_f64(&m.checked_add(&n).unwrap()).unwrap()
            <= root.value_f64(&m).unwrap() + root.value_f64(&n).unwrap() + 1e-12
    );
    assert!(root.value_f64(&m).unwrap() > 0.0);

    // Integer homogeneity fails: g(4m) = 2 g(m), not 4 g(m).
    let quadrupled = root.value_f64(&m.scale(&Z::from(4))).unwrap();
    assert!((quadrupled - 2.0 * root.value_f64(&m).unwrap()).abs() < 1e-12);
    assert!((quadrupled - 4.0 * root.value_f64(&m).unwrap()).abs() > 1.0);

    // The underlying weighted l1 does claim homogeneity, and has it.
    let norm = WeightedL1::uniform(&basis);
    assert_eq!(norm.profile(), ComplexityProfile::LatticeNorm);
    assert_eq!(
        norm.exact_value(&m.scale(&Z::from(4))).unwrap().unwrap(),
        umt::Q::new(Z::from(4), Z::from(1)) * norm.exact_value(&m).unwrap().unwrap()
    );
}

/// F6 - nonhomomorphic representative policy.
///
/// A hand-coded right inverse that violates additivity must still satisfy the
/// right-inverse and lens laws, must not claim homomorphism, and must not have
/// a direct-sum decomposition attributed to it.
#[test]
fn f06_nonhomomorphic_representative_policy() {
    let basis = five_limit();
    let ambient = AmbientLattice::new("umt:edo:12", 1);
    let map = TemperamentMap::from_rows(&basis, &ambient, [[12i64, 19, 28]]).unwrap();
    let kernel = map.kernel().clone();

    // Deliberately non-additive: shift the lift of every odd class.
    let policy = OffsetPolicy::new(
        SplitPolicy::new(LinearSplit::of(&map).unwrap()),
        move |class: &umt::temperament::ImageElem, _: &()| {
            if (&class.coordinates()[0] % 2i32) != Z::from(0) {
                kernel.element([1, 0]).ok()
            } else {
                None
            }
        },
    );

    // Right-inverse law: holds for every class.
    for coordinate in -8i64..=8 {
        let class = map.image().element([coordinate]).unwrap();
        let decision = policy.choose(&class, &()).unwrap();
        assert_eq!(map.apply_to_image(&decision.lift).unwrap(), class);
    }

    // Homomorphism law: fails, and is not claimed.
    assert!(!policy.claims_homomorphic());
    let one = map.image().element([1i64]).unwrap();
    let two = map.image().element([2i64]).unwrap();
    let lift = |class| policy.choose(class, &()).unwrap().lift;
    assert_ne!(
        lift(&two),
        lift(&one).checked_add(&lift(&one)).unwrap(),
        "this policy must not be additive"
    );

    // Lens laws: hold anyway, because they hold for any right inverse.
    let lens = StructuralLens::new(policy);
    let monzo = basis.monzo([-1, 1, 0]).unwrap();
    let class = lens.get(&monzo).unwrap();
    assert_eq!(lens.put(&monzo, &class, &()).unwrap(), monzo, "GetPut");

    let target = map.image().element([3i64]).unwrap();
    let put = lens.put(&monzo, &target, &()).unwrap();
    assert_eq!(lens.get(&put).unwrap(), target, "PutGet");
    assert_eq!(
        lens.put(&put, &target, &()).unwrap(),
        lens.put(&monzo, &target, &()).unwrap(),
        "PutPut"
    );

    // The direct-sum decomposition belongs to homomorphic splittings only.
    // `OffsetPolicy` is not a `HomomorphicSplit`, so it cannot be passed
    // anywhere one is required; the split it wraps can.
    let honest = SplitPolicy::new(LinearSplit::of(&map).unwrap());
    assert!(RepresentativePolicy::<()>::claims_homomorphic(&honest));
}

/// F7 - enharmonic spelling.
///
/// Two exact L1 objects that map to the same 12-EDO class stay distinct, and
/// their comma residues relative to the same policy differ by exactly the
/// comma that separates them.
#[test]
fn f07_enharmonic_spelling() {
    let basis = five_limit();
    let ambient = AmbientLattice::new("umt:edo:12", 1);
    let map = TemperamentMap::from_rows(&basis, &ambient, [[12i64, 19, 28]]).unwrap();
    let lens = StructuralLens::new(SplitPolicy::new(LinearSplit::of(&map).unwrap()));

    // The just fifth, and the same fifth raised by a syntonic comma.
    let fifth = basis.monzo([-1, 1, 0]).unwrap();
    let comma = basis.monzo([-4, 4, -1]).unwrap();
    let wide_fifth = fifth.checked_add(&comma).unwrap();

    // Distinct L1 objects with distinct exact ratios.
    assert_ne!(fifth, wide_fifth);
    assert_eq!(fifth.exact_ratio().unwrap().to_string(), "3/2");
    assert_eq!(wide_fifth.exact_ratio().unwrap().to_string(), "243/160");

    // Equal L2 class.
    assert_eq!(
        lens.get(&fifth).unwrap(),
        lens.get(&wide_fifth).unwrap(),
        "both spellings sound as 7 steps of 12-EDO"
    );
    assert_eq!(map.apply(&fifth).unwrap().coordinates(), &[Z::from(7)]);

    // Distinct exact comma residues, differing by exactly the comma.
    let plain = lens.residue(&fifth, &()).unwrap();
    let wide = lens.residue(&wide_fifth, &()).unwrap();
    assert_ne!(plain, wide);

    let difference = map
        .kernel()
        .embed(&wide)
        .unwrap()
        .checked_sub(&map.kernel().embed(&plain).unwrap())
        .unwrap();
    assert_eq!(difference, comma, "the residues differ by the comma itself");

    // The residue is an exact kernel element, not a real deviation.
    assert!(map.kills(&map.kernel().embed(&wide).unwrap()).unwrap());
}

/// F22 - reachable versus ambient octave classes.
///
/// With `H = 2Z`, `Gamma = Z`, and octave image 6, the reachable quotient
/// `H/6Z` is `Z/3Z` while the ambient quotient `Gamma/6Z` is `Z/6Z`. Both are
/// constructed, both record which group they were formed on, and they are not
/// identified.
#[test]
fn f22_reachable_versus_ambient_classes() {
    let basis = five_limit();
    let val = PatentVal::new(&basis, 6, NEAREST).unwrap();
    let map = val.map();
    let octave = basis.monzo([1, 0, 0]).unwrap();

    assert_eq!(val.apply(&octave).unwrap(), Z::from(6));
    assert_eq!(val.image_generator(), Z::from(2));

    let ambient = UnitEquivalence::on_ambient(map, &octave).unwrap();
    let reachable = UnitEquivalence::on_image(map, &octave).unwrap();

    assert_eq!(ambient.quotient().to_string(), "Z/6Z");
    assert_eq!(ambient.class_count(), Some(Z::from(6)));
    assert_eq!(ambient.domain(), EquivalenceDomain::Ambient);

    assert_eq!(reachable.quotient().to_string(), "Z/3Z");
    assert_eq!(reachable.class_count(), Some(Z::from(3)));
    assert_eq!(reachable.domain(), EquivalenceDomain::Image);

    assert_ne!(
        ambient.quotient(),
        reachable.quotient(),
        "reachable and ambient pitch-class groups must not be identified"
    );

    // The difference comes from the unit's coordinates in each group: six
    // ambient steps are three units of the image lattice.
    assert_eq!(ambient.unit_coordinates(), &[Z::from(6)]);
    assert_eq!(reachable.unit_coordinates(), &[Z::from(3)]);
}

/// F33 - saturation excludes the zero multiplier.
///
/// With `K = {0} <= Z`, `x = 1`, and `n = 0`, the fact that `n x = 0` lies in
/// `K` carries no information about `x`. A saturation check that quantified
/// over all integers rather than the nonzero ones would conclude that every
/// element is in every subgroup.
#[test]
fn f33_saturation_excludes_the_zero_multiplier() {
    let trivial = Sublattice::trivial(1);

    // 0 * x is in K for every x, and K is saturated, yet x is not in K.
    assert!(trivial.contains(&[Z::from(0)]).unwrap());
    assert!(trivial.is_saturated());
    assert!(!trivial.contains(&[Z::from(1)]).unwrap());

    // The same trap through a mapping: the zero map has everything in its
    // kernel, which is a different situation and must stay distinguishable.
    let domain = Basis::primes("umt:prime:2", &[2]).unwrap();
    let ambient = AmbientLattice::new("umt:f33-ambient", 1);
    let identity = TemperamentMap::from_rows(&domain, &ambient, [[1i64]]).unwrap();
    let zero_map = TemperamentMap::from_rows(&domain, &ambient, [[0i64]]).unwrap();

    let unit = domain.monzo([1]).unwrap();
    assert!(!identity.kills(&unit).unwrap());
    assert!(zero_map.kills(&unit).unwrap());
    assert_eq!(identity.kernel().rank(), 0);
    assert_eq!(zero_map.kernel().rank(), 1);
}

/// F26 - unattained optimization infimum.
///
/// With admissible set `(0, 1)` and objective `J(y) = y`, the infimum is 0 and
/// the minimizer set is empty. The optimizer must report both facts and must
/// not fabricate a `y*`.
#[test]
fn f26_unattained_optimization_infimum() {
    /// A declared interval, with endpoints included or not.
    #[derive(Clone, Copy)]
    struct Interval {
        lower: f64,
        upper: f64,
        lower_included: bool,
    }

    /// Minimizes `J(y) = y` over the interval, honestly.
    fn minimize(domain: Interval) -> OptimizationOutcome<f64, f64> {
        if domain.lower > domain.upper || (domain.lower == domain.upper && !domain.lower_included) {
            return OptimizationOutcome::Infeasible;
        }
        if domain.lower_included {
            OptimizationOutcome::Exact {
                solution: domain.lower,
                cost: domain.lower,
            }
        } else {
            // The greatest lower bound is known; nothing attains it.
            OptimizationOutcome::InfimumNotAttained {
                infimum: domain.lower,
            }
        }
    }

    // The fixture's case: the open interval (0, 1).
    let open = Interval {
        lower: 0.0,
        upper: 1.0,
        lower_included: false,
    };
    let outcome = minimize(open);
    assert_eq!(
        outcome,
        OptimizationOutcome::InfimumNotAttained { infimum: 0.0 }
    );
    assert_eq!(outcome.cost(), Some(&0.0), "the infimum is reported");
    assert_eq!(outcome.solution(), None, "no minimizer is fabricated");
    assert!(!outcome.is_optimal());
    assert!(!outcome.has_solution());

    // The closed interval does attain it, and says so differently.
    let closed = Interval {
        lower_included: true,
        ..open
    };
    assert!(minimize(closed).is_optimal());
    assert_eq!(minimize(closed).solution(), Some(&0.0));

    // An empty admissible set is a third, distinct outcome.
    let empty = Interval {
        lower: 1.0,
        upper: 0.0,
        lower_included: true,
    };
    assert_eq!(minimize(empty), OptimizationOutcome::Infeasible);
    assert_eq!(minimize(empty).cost(), None);
}

/// F28 - context-dependent realization typing.
///
/// One structural pitch point, realized differently under different
/// instrument and time contexts. The realization is `Phi(x, c)`, with the
/// context an explicit parameter, and it must not claim to be a regular
/// homomorphism.
#[test]
fn f28_context_dependent_realization_typing() {
    /// Register-dependent stretch, as on a real piano.
    struct StretchedPiano {
        base: PitchRealization<AmbientLattice>,
        cents_per_octave_squared: f64,
    }

    /// What the realization depends on beyond the pitch itself.
    struct PerformanceContext {
        stretch_enabled: bool,
    }

    impl PitchRealizer<umt::temperament::AmbientElem, PerformanceContext> for StretchedPiano {
        type Error = umt::error::PitchError;

        fn realize(
            &self,
            point: &PitchPoint<umt::temperament::AmbientElem>,
            context: &PerformanceContext,
        ) -> Result<LogFrequency, Self::Error> {
            let plain = self.base.realize_point(point)?;
            if !context.stretch_enabled {
                return Ok(plain);
            }
            // Stretch grows with the square of the distance from the
            // reference, which no homomorphism can do.
            let distance = self.base.realized_reference().interval_to(plain).get();
            let stretch = Cents::new(self.cents_per_octave_squared * distance * distance)?;
            Ok(plain.translate(Octaves::from(stretch)))
        }

        fn is_regular(&self) -> bool {
            false
        }
    }

    let steps = AmbientLattice::new("umt:edo:12", 1);
    let tuning = RegularTuning::equal_divisions(&steps, 12).unwrap();
    let reference = PitchPoint::new(PitchOrigin::new("umt:origin:a4"), steps.zero());
    let base = PitchRealization::new(
        tuning,
        reference.clone(),
        FrequencyHz::new(440.0).unwrap().log_frequency(),
    );
    let piano = StretchedPiano {
        base,
        cents_per_octave_squared: 3.0,
    };

    // One structural point, two contexts, two different realizations.
    let two_octaves_up = reference
        .translate(&steps.element([24i64]).unwrap())
        .unwrap();
    let plain = piano
        .realize(
            &two_octaves_up,
            &PerformanceContext {
                stretch_enabled: false,
            },
        )
        .unwrap();
    let stretched = piano
        .realize(
            &two_octaves_up,
            &PerformanceContext {
                stretch_enabled: true,
            },
        )
        .unwrap();

    assert_ne!(plain, stretched);
    assert!(stretched.frequency().unwrap().get() > plain.frequency().unwrap().get());

    // It does not claim regularity, and it is indeed not additive: the
    // stretch at two octaves is not twice the stretch at one.
    assert!(!piano.is_regular());
    let one_octave_up = reference
        .translate(&steps.element([12i64]).unwrap())
        .unwrap();
    let context = PerformanceContext {
        stretch_enabled: true,
    };
    let one = piano.realize(&one_octave_up, &context).unwrap();
    let two = piano.realize(&two_octaves_up, &context).unwrap();
    let first_octave = piano.base.realized_reference().interval_to(one).get();
    let both_octaves = piano.base.realized_reference().interval_to(two).get();
    assert!(
        (both_octaves - 2.0 * first_octave).abs() > 1e-6,
        "a contextual realization need not be additive, and this one is not"
    );

    // The regular realization it wraps does claim regularity, correctly.
    assert!(PitchRealizer::<_, PerformanceContext>::is_regular(
        &piano.base
    ));
}

/// F31 - a regular interval tuning requires a point reference.
///
/// Interval sizes are available from `tau` alone; absolute pitch points are
/// not realized until reference data determine the affine map `tau_hat`.
#[test]
fn f31_regular_tuning_requires_a_point_reference() {
    let steps = AmbientLattice::new("umt:edo:12", 1);
    let tuning = RegularTuning::equal_divisions(&steps, 12).unwrap();

    // Intervals: fully evaluable.
    for (count, expected) in [(0i64, 0.0), (7, 700.0), (-12, -1200.0)] {
        let size = Cents::from(tuning.size(&steps.element([count]).unwrap()).unwrap());
        assert!((size.get() - expected).abs() < 1e-9, "{count} steps");
    }

    // Points: not evaluable from the tuning. The only way to realize one is
    // to build a `PitchRealization`, which requires both a structural and a
    // realized reference; there is no constructor that omits them.
    let origin = PitchOrigin::new("umt:origin:a4");
    let reference = PitchPoint::new(origin.clone(), steps.zero());
    let realization = PitchRealization::new(
        tuning,
        reference.clone(),
        FrequencyHz::new(440.0).unwrap().log_frequency(),
    );

    assert_eq!(
        realization.realize_point(&reference).unwrap(),
        realization.realized_reference(),
        "the reference point realizes to the reference pitch"
    );

    let up_a_fifth = reference
        .translate(&steps.element([7i64]).unwrap())
        .unwrap();
    let hz = realization
        .realize_point(&up_a_fifth)
        .unwrap()
        .frequency()
        .unwrap()
        .get();
    assert!((hz - 659.255_113_8).abs() < 1e-6, "{hz}");

    // Changing the realized reference changes pitches, not intervals: concert
    // pitch is reference data, not a property of the lattice.
    let baroque = realization.with_concert_pitch(FrequencyHz::new(415.0).unwrap().log_frequency());
    let baroque_hz = baroque
        .realize_point(&up_a_fifth)
        .unwrap()
        .frequency()
        .unwrap()
        .get();
    assert!(baroque_hz < hz);
    assert_eq!(
        baroque.tuning(),
        realization.tuning(),
        "the interval tuning is untouched"
    );
}

/// Prompt section 13: mandatory equal-division cases.
#[test]
fn edo_mandatory_cases() {
    let basis = five_limit();

    // Ordinary 12-EDO.
    let twelve = PatentVal::new(&basis, 12, NEAREST).unwrap();
    assert_eq!(twelve.entries(), &[Z::from(12), Z::from(19), Z::from(28)]);

    // 6-EDO.
    let six = PatentVal::new(&basis, 6, NEAREST).unwrap();
    assert_eq!(six.entries(), &[Z::from(6), Z::from(10), Z::from(14)]);

    // Zero map.
    let zero = PatentVal::new(&basis, 0, NEAREST).unwrap();
    assert_eq!(zero.entries(), &[Z::from(0), Z::from(0), Z::from(0)]);
    assert_eq!(zero.image_generator(), Z::from(0));
    assert_eq!(zero.image_rank(), 0);
    assert!(!zero.is_surjective());
    assert_eq!(zero.map().kernel().rank(), 3);

    // The octave entry is fixed to N.
    for divisions in [0u32, 1, 5, 6, 12, 19, 31, 41, 53, 72, 311, 1200] {
        let val = PatentVal::new(&basis, divisions, NEAREST).unwrap();
        assert_eq!(val.entries()[0], Z::from(divisions));
    }
}

/// UMT-3.2 section 1.6 places no surjectivity requirement on a patent val, and
/// section 1.4.2 keeps surjectivity separate from kernel saturation.
#[test]
fn patent_vals_are_not_assumed_surjective() {
    let basis = five_limit();
    let non_surjective: Vec<u32> = (1..=48)
        .filter(|divisions| {
            !PatentVal::new(&basis, *divisions, NEAREST)
                .unwrap()
                .is_surjective()
        })
        .collect();
    assert!(
        non_surjective.contains(&6),
        "6-EDO must be among the non-surjective 5-limit patent vals, found {non_surjective:?}"
    );
}
