//! UMT-3.2 conformance fixtures (specification section 9.13).
//!
//! `docs/conformance.md` maps every fixture to its test and status. Fixtures
//! whose machinery is not implemented yet are absent from this file rather
//! than stubbed, because a skipped law must never look like a passing one
//! (prompt section 60, item 20).
//!
//! Tests named `*_partial` cover the part of a fixture that the implemented
//! layers can decide. The remaining obligations are listed in the docs table.

use std::sync::Arc;

use umt::algebra::lattice::Sublattice;
use umt::error::TemperamentError;
use umt::temperament::{
    AmbientLattice, HomomorphicSplit, KernelLattice, LinearSplit, OffsetPolicy,
    RepresentativePolicy, SaturationPolicy, SplitPolicy, StructuralLens, TemperamentMap,
};
use umt::{Basis, IntMatrix, PatentVal, RoundingConvention, Z};

const NEAREST: RoundingConvention = RoundingConvention::NearestHalfAwayFromZero;

fn five_limit() -> Arc<Basis> {
    Basis::primes("umt:prime:2.3.5", &[2, 3, 5]).expect("valid prime basis")
}

/// F1 - kernel saturation versus surjectivity.
///
/// `V = [2] : Z -> Z` has trivial, hence saturated, kernel, while its image is
/// `2Z` and the mapping is not surjective. The two properties are independent,
/// and the gcd-of-minors condition that governs surjectivity says nothing
/// about the kernel (UMT-3.2 section 1.4.2).
#[test]
fn f01_kernel_saturation_versus_surjectivity() {
    let domain = Basis::primes("umt:prime:2", &[2]).unwrap();
    let ambient = AmbientLattice::new("umt:f01-ambient", 1);
    let map = TemperamentMap::from_rows(&domain, &ambient, [[2i64]]).unwrap();

    // Kernel is trivial and therefore saturated.
    assert_eq!(map.kernel().rank(), 0);
    assert!(map.kernel().is_saturated());
    assert!(!map.kills(&domain.monzo([1]).unwrap()).unwrap());

    // Image is 2Z: rank 1, but not the whole ambient lattice.
    assert_eq!(map.image().rank(), 1);
    assert!(!map.is_surjective());
    assert_eq!(
        map.image().basis(),
        &IntMatrix::from_rows([[2i64]]).unwrap()
    );
    assert_eq!(map.invariant_factors(), &[Z::from(2)]);

    let odd = ambient.element([1i64]).unwrap();
    assert!(!map.image().contains(&odd).unwrap());
}

/// F2 - unsaturated direct comma subgroup.
///
/// The subgroup generated by twice a primitive comma has 2-torsion in its
/// quotient. The direct-comma validator must report it; the map-derived-kernel
/// path must not have that validator applied to it, since such a kernel is
/// saturated as a theorem (UMT-3.2 sections 1.4.1 and 1.5).
#[test]
fn f02_unsaturated_direct_comma_subgroup() {
    let basis = five_limit();
    let doubled_comma = IntMatrix::from_rows([[-8i64], [8], [-2]]).unwrap();

    // Rejecting policy: reported as unsaturated, with the torsion order.
    assert_eq!(
        KernelLattice::from_direct_commas(&basis, &doubled_comma, SaturationPolicy::Reject)
            .unwrap_err(),
        TemperamentError::UnsaturatedCommaSubgroup {
            torsion_invariants: vec![Z::from(2)]
        }
    );

    // Saturating policy: replaced, and the change is reported.
    let (saturated, report) =
        KernelLattice::from_direct_commas(&basis, &doubled_comma, SaturationPolicy::Saturate)
            .unwrap();
    assert!(!report.was_saturated);
    assert_eq!(report.torsion_invariants, vec![Z::from(2)]);
    assert_eq!(report.rank, 1);
    assert!(saturated.is_saturated());
    // The comma itself is now in the subgroup; it was not before.
    let comma = basis.monzo([-4, 4, -1]).unwrap();
    assert!(saturated.contains(&comma).unwrap());
    let (unsaturated, _) =
        KernelLattice::from_direct_commas(&basis, &doubled_comma, SaturationPolicy::Saturate)
            .unwrap();
    assert!(
        unsaturated.is_saturated(),
        "the returned lattice is the saturation"
    );

    // The map-derived kernel of a mapping that tempers out the doubled comma
    // is the saturated one, and no saturation validation was applied to it.
    let ambient = AmbientLattice::new("umt:edo:12", 1);
    let map = TemperamentMap::from_rows(&basis, &ambient, [[12i64, 19, 28]]).unwrap();
    assert!(map.kernel().is_saturated());
    assert!(map.kernel().contains(&comma).unwrap());
}

/// F3 - 12-EDO quotient (partial).
///
/// Covered here: the syntonic and Pythagorean commas are both killed, the
/// kernel has rank 2 so the reachable quotient is free of rank 1, the image is
/// all of `Z`, and the octave maps to 12 steps.
///
/// Not covered yet: unit equivalence as a constructed quotient object, so
/// `Z/12Z` is asserted as an index rather than built (UMT-3.2 section 1.9).
#[test]
fn f03_twelve_edo_quotient_partial() {
    let basis = five_limit();
    let ambient = AmbientLattice::new("umt:edo:12", 1);
    let map = TemperamentMap::from_rows(&basis, &ambient, [[12i64, 19, 28]]).unwrap();

    let syntonic = basis.monzo([-4, 4, -1]).unwrap();
    let pythagorean = basis.monzo([-19, 12, 0]).unwrap();
    assert!(map.kills(&syntonic).unwrap());
    assert!(map.kills(&pythagorean).unwrap());

    // rank(Lambda_B) - rank(K) = 1, and T is isomorphic to H, which is Z.
    assert_eq!(basis.rank() - map.kernel().rank(), 1);
    assert_eq!(map.image().rank(), 1);
    assert!(map.image().is_full(), "H = Gamma = Z");

    // Both commas generate the kernel between them.
    let kernel_from_commas = KernelLattice::of_map(
        &basis,
        &IntMatrix::from_rows([[-4i64, -19], [4, 12], [-1, 0]]).unwrap(),
    )
    .unwrap();
    assert_eq!(&kernel_from_commas, map.kernel());

    // Octave maps to 12 steps, so ambient unit equivalence has index 12.
    let octave = basis.monzo([1, 0, 0]).unwrap();
    assert_eq!(map.apply(&octave).unwrap().coordinates(), &[Z::from(12)]);
}

/// F4 - 6-EDO image.
///
/// The ambient step lattice `Gamma = Z` and the mapped image `H = 2Z` are
/// separately represented, and detempering is defined only on `H`: an odd
/// ambient step cannot even be turned into a class to ask a policy about, so
/// there is no automatic L1 detempering for it.
#[test]
fn f04_6edo_image() {
    let basis = five_limit();
    let val = PatentVal::new(&basis, 6, NEAREST).unwrap();

    assert_eq!(
        val.entries(),
        &[Z::from(6), Z::from(10), Z::from(14)],
        "the usual 5-limit patent val for 6-EDO"
    );

    // Image is 2Z, a proper subgroup of the ambient Z.
    assert_eq!(val.image_generator(), Z::from(2));
    assert!(!val.is_surjective());
    assert_eq!(
        val.map().image().basis(),
        &IntMatrix::from_rows([[2i64]]).unwrap()
    );

    // Odd ambient steps exist but are not reached.
    for odd in [-5i64, -3, -1, 1, 3, 5, 7] {
        let step = Z::from(odd);
        assert!(!val.contains_ambient(&step), "step {odd} must not be in H");
        assert_eq!(
            val.image_coordinate(&step),
            Err(TemperamentError::NotInImage {
                coordinates: vec![Z::from(odd)]
            }),
            "step {odd} has no automatic L1 detempering"
        );
    }

    // Even steps are reached, and their intrinsic image coordinates differ
    // from their ambient coordinates.
    for even in [-4i64, -2, 0, 2, 4, 6] {
        let step = Z::from(even);
        assert!(val.contains_ambient(&step));
        let coordinate = val.image_coordinate(&step).unwrap();
        assert_eq!(coordinate, Z::from(even / 2));
        assert_eq!(val.embed_image(&coordinate).unwrap(), step);
    }

    // Detempering is defined on H, and only on H. A representative policy
    // takes an `ImageElem`, which an odd ambient step cannot produce, so the
    // failure happens before any policy is consulted.
    let map = val.map();
    let split = LinearSplit::of(map).unwrap();
    for even in [-4i64, -2, 0, 2, 4, 6] {
        let class = map
            .image()
            .from_ambient(&map.ambient().element([even]).unwrap())
            .unwrap();
        let lift = split.split(&class).unwrap();
        assert_eq!(map.apply(&lift).unwrap().coordinates(), &[Z::from(even)]);
    }
    for odd in [-3i64, -1, 1, 3] {
        assert!(
            map.image()
                .from_ambient(&map.ambient().element([odd]).unwrap())
                .is_err(),
            "an odd step is not a class, so no lift can be requested for it"
        );
    }
}

/// F6 - nonhomomorphic representative policy.
///
/// A hand-coded right inverse that violates additivity must still satisfy the
/// right-inverse and lens laws, must not claim homomorphism, and must not have
/// a direct-sum decomposition attributed to it.
#[test]
fn f06_nonhomomorphic_representative_policy() {
    let basis = five_limit();
    let ambient = AmbientLattice::new("umt:edo:12", 1);
    let map = TemperamentMap::from_rows(&basis, &ambient, [[12i64, 19, 28]]).unwrap();
    let kernel = map.kernel().clone();

    // Deliberately non-additive: shift the lift of every odd class.
    let policy = OffsetPolicy::new(
        SplitPolicy::new(LinearSplit::of(&map).unwrap()),
        move |class: &umt::temperament::ImageElem, _: &()| {
            if (&class.coordinates()[0] % 2i32) != Z::from(0) {
                kernel.element([1, 0]).ok()
            } else {
                None
            }
        },
    );

    // Right-inverse law: holds for every class.
    for coordinate in -8i64..=8 {
        let class = map.image().element([coordinate]).unwrap();
        let decision = policy.choose(&class, &()).unwrap();
        assert_eq!(map.apply_to_image(&decision.lift).unwrap(), class);
    }

    // Homomorphism law: fails, and is not claimed.
    assert!(!policy.claims_homomorphic());
    let one = map.image().element([1i64]).unwrap();
    let two = map.image().element([2i64]).unwrap();
    let lift = |class| policy.choose(class, &()).unwrap().lift;
    assert_ne!(
        lift(&two),
        lift(&one).checked_add(&lift(&one)).unwrap(),
        "this policy must not be additive"
    );

    // Lens laws: hold anyway, because they hold for any right inverse.
    let lens = StructuralLens::new(policy);
    let monzo = basis.monzo([-1, 1, 0]).unwrap();
    let class = lens.get(&monzo).unwrap();
    assert_eq!(lens.put(&monzo, &class, &()).unwrap(), monzo, "GetPut");

    let target = map.image().element([3i64]).unwrap();
    let put = lens.put(&monzo, &target, &()).unwrap();
    assert_eq!(lens.get(&put).unwrap(), target, "PutGet");
    assert_eq!(
        lens.put(&put, &target, &()).unwrap(),
        lens.put(&monzo, &target, &()).unwrap(),
        "PutPut"
    );

    // The direct-sum decomposition belongs to homomorphic splittings only.
    // `OffsetPolicy` is not a `HomomorphicSplit`, so it cannot be passed
    // anywhere one is required; the split it wraps can.
    let honest = SplitPolicy::new(LinearSplit::of(&map).unwrap());
    assert!(RepresentativePolicy::<()>::claims_homomorphic(&honest));
}

/// F7 - enharmonic spelling.
///
/// Two exact L1 objects that map to the same 12-EDO class stay distinct, and
/// their comma residues relative to the same policy differ by exactly the
/// comma that separates them.
#[test]
fn f07_enharmonic_spelling() {
    let basis = five_limit();
    let ambient = AmbientLattice::new("umt:edo:12", 1);
    let map = TemperamentMap::from_rows(&basis, &ambient, [[12i64, 19, 28]]).unwrap();
    let lens = StructuralLens::new(SplitPolicy::new(LinearSplit::of(&map).unwrap()));

    // The just fifth, and the same fifth raised by a syntonic comma.
    let fifth = basis.monzo([-1, 1, 0]).unwrap();
    let comma = basis.monzo([-4, 4, -1]).unwrap();
    let wide_fifth = fifth.checked_add(&comma).unwrap();

    // Distinct L1 objects with distinct exact ratios.
    assert_ne!(fifth, wide_fifth);
    assert_eq!(fifth.exact_ratio().unwrap().to_string(), "3/2");
    assert_eq!(wide_fifth.exact_ratio().unwrap().to_string(), "243/160");

    // Equal L2 class.
    assert_eq!(
        lens.get(&fifth).unwrap(),
        lens.get(&wide_fifth).unwrap(),
        "both spellings sound as 7 steps of 12-EDO"
    );
    assert_eq!(map.apply(&fifth).unwrap().coordinates(), &[Z::from(7)]);

    // Distinct exact comma residues, differing by exactly the comma.
    let plain = lens.residue(&fifth, &()).unwrap();
    let wide = lens.residue(&wide_fifth, &()).unwrap();
    assert_ne!(plain, wide);

    let difference = map
        .kernel()
        .embed(&wide)
        .unwrap()
        .checked_sub(&map.kernel().embed(&plain).unwrap())
        .unwrap();
    assert_eq!(difference, comma, "the residues differ by the comma itself");

    // The residue is an exact kernel element, not a real deviation.
    assert!(map.kills(&map.kernel().embed(&wide).unwrap()).unwrap());
}

/// F22 - reachable versus ambient octave classes (partial).
///
/// With `H = 2Z`, `Gamma = Z`, and octave image 6, the reachable quotient
/// `H/6Z` has 3 elements while the ambient quotient `Gamma/6Z` has 6. The two
/// counts are derived from the represented image, not asserted as constants.
///
/// Not covered yet: the quotient groups as constructed objects.
#[test]
fn f22_reachable_versus_ambient_classes_partial() {
    let basis = five_limit();
    let val = PatentVal::new(&basis, 6, NEAREST).unwrap();

    let octave_image = val.apply(&basis.monzo([1, 0, 0]).unwrap()).unwrap();
    assert_eq!(octave_image, Z::from(6));

    let image_generator = val.image_generator();
    assert_eq!(image_generator, Z::from(2));

    // |Gamma / 6Z| = 6, and |H / 6Z| = |2Z / 6Z| = 6 / 2 = 3.
    let ambient_classes = octave_image.clone();
    let reachable_classes = &octave_image / &image_generator;

    assert_eq!(ambient_classes, Z::from(6));
    assert_eq!(reachable_classes, Z::from(3));
    assert_ne!(
        ambient_classes, reachable_classes,
        "reachable and ambient pitch-class counts must not be identified"
    );
}

/// F33 - saturation excludes the zero multiplier.
///
/// With `K = {0} <= Z`, `x = 1`, and `n = 0`, the fact that `n x = 0` lies in
/// `K` carries no information about `x`. A saturation check that quantified
/// over all integers rather than the nonzero ones would conclude that every
/// element is in every subgroup.
#[test]
fn f33_saturation_excludes_the_zero_multiplier() {
    let trivial = Sublattice::trivial(1);

    // 0 * x is in K for every x, and K is saturated, yet x is not in K.
    assert!(trivial.contains(&[Z::from(0)]).unwrap());
    assert!(trivial.is_saturated());
    assert!(!trivial.contains(&[Z::from(1)]).unwrap());

    // The same trap through a mapping: the zero map has everything in its
    // kernel, which is a different situation and must stay distinguishable.
    let domain = Basis::primes("umt:prime:2", &[2]).unwrap();
    let ambient = AmbientLattice::new("umt:f33-ambient", 1);
    let identity = TemperamentMap::from_rows(&domain, &ambient, [[1i64]]).unwrap();
    let zero_map = TemperamentMap::from_rows(&domain, &ambient, [[0i64]]).unwrap();

    let unit = domain.monzo([1]).unwrap();
    assert!(!identity.kills(&unit).unwrap());
    assert!(zero_map.kills(&unit).unwrap());
    assert_eq!(identity.kernel().rank(), 0);
    assert_eq!(zero_map.kernel().rank(), 1);
}

/// Prompt section 13: mandatory equal-division cases.
#[test]
fn edo_mandatory_cases() {
    let basis = five_limit();

    // Ordinary 12-EDO.
    let twelve = PatentVal::new(&basis, 12, NEAREST).unwrap();
    assert_eq!(twelve.entries(), &[Z::from(12), Z::from(19), Z::from(28)]);

    // 6-EDO.
    let six = PatentVal::new(&basis, 6, NEAREST).unwrap();
    assert_eq!(six.entries(), &[Z::from(6), Z::from(10), Z::from(14)]);

    // Zero map.
    let zero = PatentVal::new(&basis, 0, NEAREST).unwrap();
    assert_eq!(zero.entries(), &[Z::from(0), Z::from(0), Z::from(0)]);
    assert_eq!(zero.image_generator(), Z::from(0));
    assert_eq!(zero.image_rank(), 0);
    assert!(!zero.is_surjective());
    assert_eq!(zero.map().kernel().rank(), 3);

    // The octave entry is fixed to N.
    for divisions in [0u32, 1, 5, 6, 12, 19, 31, 41, 53, 72, 311, 1200] {
        let val = PatentVal::new(&basis, divisions, NEAREST).unwrap();
        assert_eq!(val.entries()[0], Z::from(divisions));
    }
}

/// UMT-3.2 section 1.6 places no surjectivity requirement on a patent val, and
/// section 1.4.2 keeps surjectivity separate from kernel saturation.
#[test]
fn patent_vals_are_not_assumed_surjective() {
    let basis = five_limit();
    let non_surjective: Vec<u32> = (1..=48)
        .filter(|divisions| {
            !PatentVal::new(&basis, *divisions, NEAREST)
                .unwrap()
                .is_surjective()
        })
        .collect();
    assert!(
        non_surjective.contains(&6),
        "6-EDO must be among the non-surjective 5-limit patent vals, found {non_surjective:?}"
    );
}
