//! Regular temperament mappings (UMT-3.2 section 1.4).
//!
//! A mapping is an integer homomorphism `V: Lambda_B -> Gamma`. It need not be
//! surjective, and it is not a tuning: it sends lattice elements to integer
//! ambient coordinates, never to real interval sizes.

use alloc::sync::Arc;
use alloc::vec::Vec;

use num_integer::Integer;
use num_traits::Zero;

use crate::algebra::Z;
use crate::algebra::lattice::Sublattice;
use crate::algebra::matrix::IntMatrix;
use crate::algebra::normal_form::SmithNormalForm;
use crate::error::TemperamentError;
use crate::proportion::basis::Basis;
use crate::proportion::monzo::{Monzo, compatible};
use crate::temperament::image::{AmbientElem, AmbientLattice, ImageElem, ImageLattice};
use crate::temperament::kernel::KernelLattice;

/// The unvalidated form of a [`TemperamentMap`].
///
/// Holds exactly the declared data, with no derived structure and no shape
/// guarantee. Validation happens in [`TemperamentMap::new`] (prompt section
/// 12).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RawTemperamentMap {
    /// The domain basis `B`, spanning `Lambda_B`.
    pub domain: Arc<Basis>,
    /// The declared ambient lattice `Gamma`.
    pub ambient: Arc<AmbientLattice>,
    /// The mapping matrix, with one row per ambient coordinate and one column
    /// per basis generator.
    pub matrix: IntMatrix,
}

/// A validated regular temperament mapping `V: Lambda_B -> Gamma`.
///
/// UMT layer: L2 structural map, exact.
///
/// Construction computes the derived structure eagerly, so a validated mapping
/// always knows its rank, invariant factors, image, and kernel, and no
/// interior mutability or lazy cache is involved. Equality is presentation
/// equality over the domain, the ambient lattice, and the matrix; two matrices
/// that temper out the same commas are *not* equal, and
/// [`TemperamentMap::kernel`] comparison is the honest test for that.
///
/// # Examples
///
/// ```
/// use umt::temperament::{AmbientLattice, TemperamentMap};
/// use umt::{Basis, IntMatrix};
///
/// let basis = Basis::primes("umt:prime:2.3.5", &[2, 3, 5])?;
/// let steps = AmbientLattice::new("umt:edo:12", 1);
/// let map = TemperamentMap::from_rows(&basis, &steps, [[12i64, 19, 28]])?;
///
/// // Rank 1 mapping of a rank 3 lattice: the kernel has rank 2.
/// assert_eq!(map.rank(), 1);
/// assert_eq!(map.kernel().rank(), 2);
/// assert!(map.is_surjective());
///
/// // The syntonic comma is tempered out; the just fifth is not.
/// assert!(map.kills(&basis.monzo([-4, 4, -1])?)?);
/// assert!(!map.kills(&basis.monzo([-1, 1, 0])?)?);
///
/// // A map-derived kernel is saturated as a theorem, not as a check.
/// assert!(map.kernel().is_saturated());
/// # Ok::<(), Box<dyn core::error::Error>>(())
/// ```
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TemperamentMap {
    domain: Arc<Basis>,
    ambient: Arc<AmbientLattice>,
    matrix: IntMatrix,
    smith: SmithNormalForm,
    image: Arc<ImageLattice>,
    kernel: Arc<KernelLattice>,
}

impl TemperamentMap {
    /// Validates a raw mapping and computes its derived structure.
    ///
    /// # Errors
    ///
    /// Returns [`TemperamentError::ShapeMismatch`] if the matrix shape does
    /// not match the domain and ambient ranks.
    pub fn new(raw: RawTemperamentMap) -> Result<Self, TemperamentError> {
        let RawTemperamentMap {
            domain,
            ambient,
            matrix,
        } = raw;

        if matrix.rows() != ambient.rank() || matrix.cols() != domain.rank() {
            return Err(TemperamentError::ShapeMismatch {
                expected_rows: ambient.rank(),
                expected_cols: domain.rank(),
                found_rows: matrix.rows(),
                found_cols: matrix.cols(),
            });
        }

        // The image is generated by the columns of the matrix.
        let image = ImageLattice::new(
            &ambient,
            Sublattice::from_generators(ambient.rank(), &matrix)?,
        )?;

        // The kernel comes from the Smith normal form. It is saturated
        // automatically because the ambient group is torsion-free (UMT-3.2
        // section 1.4.1), so it is built through the map-kernel constructor,
        // which performs no redundant saturation check.
        let smith = SmithNormalForm::of(&matrix);
        let kernel = KernelLattice::of_map(&domain, &smith.kernel_basis())?;

        Ok(Self {
            domain,
            ambient,
            matrix,
            smith,
            image,
            kernel,
        })
    }

    /// Builds a mapping from rows of integers.
    ///
    /// # Errors
    ///
    /// Returns [`TemperamentError::Matrix`] if the rows are ragged, and
    /// [`TemperamentError::ShapeMismatch`] if the resulting shape does not
    /// match the declared ranks.
    pub fn from_rows<R, C, T>(
        domain: &Arc<Basis>,
        ambient: &Arc<AmbientLattice>,
        rows: R,
    ) -> Result<Self, TemperamentError>
    where
        R: IntoIterator<Item = C>,
        C: IntoIterator<Item = T>,
        T: Into<Z>,
    {
        Self::new(RawTemperamentMap {
            domain: Arc::clone(domain),
            ambient: Arc::clone(ambient),
            matrix: IntMatrix::from_rows(rows)?,
        })
    }

    /// The domain basis.
    #[must_use]
    pub fn domain(&self) -> &Arc<Basis> {
        &self.domain
    }

    /// The declared ambient lattice `Gamma`.
    #[must_use]
    pub fn ambient(&self) -> &Arc<AmbientLattice> {
        &self.ambient
    }

    /// The exact mapping matrix.
    #[must_use]
    pub fn matrix(&self) -> &IntMatrix {
        &self.matrix
    }

    /// The rank of the mapping, equal to the rank of its image.
    #[must_use]
    pub fn rank(&self) -> usize {
        self.smith.rank()
    }

    /// The Smith normal form of the mapping matrix, computed at construction.
    ///
    /// Exposed because exact preimage solving and homomorphic splittings are
    /// built from it. Its transformation matrices are not canonical, so
    /// nothing that must be reproducible should depend on them; the invariant
    /// factors and rank are canonical and are exposed directly.
    #[must_use]
    pub fn smith(&self) -> &SmithNormalForm {
        &self.smith
    }

    /// The invariant factors of the mapping matrix.
    ///
    /// These describe image primitivity: for a full-row-rank mapping their
    /// product is the gcd of the maximal minors, so the mapping is surjective
    /// exactly when they are all 1 and the rank equals the ambient rank
    /// (UMT-3.2 section 1.4.2). They say nothing about kernel saturation,
    /// which is automatic.
    #[must_use]
    pub fn invariant_factors(&self) -> &[Z] {
        self.smith.invariant_factors()
    }

    /// The reachable image `H = im(V)`.
    #[must_use]
    pub fn image(&self) -> &Arc<ImageLattice> {
        &self.image
    }

    /// The kernel `K = ker(V)`, the group of tempered-out commas.
    #[must_use]
    pub fn kernel(&self) -> &Arc<KernelLattice> {
        &self.kernel
    }

    /// Whether the mapping reaches all of the ambient lattice.
    #[must_use]
    pub fn is_surjective(&self) -> bool {
        self.image.is_full()
    }

    /// Applies the mapping, giving an ambient coordinate.
    ///
    /// # Errors
    ///
    /// Returns [`TemperamentError::BasisMismatch`] if the monzo is over an
    /// unrelated basis.
    pub fn apply(&self, monzo: &Monzo) -> Result<AmbientElem, TemperamentError> {
        if !compatible(monzo.basis(), &self.domain) {
            return Err(TemperamentError::BasisMismatch {
                expected: self.domain.id().clone(),
                found: monzo.basis().id().clone(),
            });
        }
        let coordinates = self.matrix.apply(monzo.exponents())?;
        self.ambient.element(coordinates)
    }

    /// Applies the mapping, giving intrinsic image coordinates.
    ///
    /// Every mapped element is in the image by construction, so this fails
    /// only on a basis mismatch.
    ///
    /// # Errors
    ///
    /// Returns [`TemperamentError::BasisMismatch`] if the monzo is over an
    /// unrelated basis.
    pub fn apply_to_image(&self, monzo: &Monzo) -> Result<ImageElem, TemperamentError> {
        let ambient = self.apply(monzo)?;
        self.image.from_ambient(&ambient)
    }

    /// The canonical exact preimage of an ambient element.
    ///
    /// This solves `V(m) = target` over the integers. The solution is not
    /// unique - every element of `m + K` is also a preimage - so the result is
    /// reduced to the canonical representative of that coset under
    /// [`crate::algebra::Sublattice::reduce_reversed`], which makes it
    /// independent of the non-canonical Smith transformation matrices used to
    /// find it and keeps the high-generator exponents small. For 12-EDO over
    /// the 5-limit basis, the class of seven steps comes back as `3/2`.
    ///
    /// Canonical is not the same as musically preferred. This is the lift that
    /// falls out of the arithmetic, not a spelling: choosing among the fiber on
    /// purpose is what a [`crate::temperament::RepresentativePolicy`] is for.
    ///
    /// # Errors
    ///
    /// Returns [`TemperamentError::NotInImage`] if the target is unreachable,
    /// and [`TemperamentError::AmbientMismatch`] if it belongs to a different
    /// ambient lattice.
    pub fn preimage(&self, target: &AmbientElem) -> Result<Monzo, TemperamentError> {
        if !self.ambient.same_identity(target.lattice()) {
            return Err(TemperamentError::AmbientMismatch {
                expected: self.ambient.id().clone(),
                found: target.lattice().id().clone(),
            });
        }

        // With `U A V = D`, solving `A p = b` means solving `D z = U b` and
        // taking `p = V z`.
        let transformed = self.smith.left().apply(target.coordinates())?;
        let factors = self.smith.invariant_factors();
        let rank = factors.len();

        let mut solution = Vec::with_capacity(self.matrix.cols());
        for (index, factor) in factors.iter().enumerate() {
            let (quotient, remainder) = transformed[index].div_rem(factor);
            if !remainder.is_zero() {
                return Err(TemperamentError::NotInImage {
                    coordinates: target.coordinates().to_vec(),
                });
            }
            solution.push(quotient);
        }
        for value in &transformed[rank..] {
            if !value.is_zero() {
                return Err(TemperamentError::NotInImage {
                    coordinates: target.coordinates().to_vec(),
                });
            }
        }
        solution.resize(self.matrix.cols(), Z::zero());

        let exponents = self.smith.right().apply(&solution)?;
        let reduced = self.kernel.sublattice().reduce_reversed(&exponents)?;
        Ok(Monzo::new(Arc::clone(&self.domain), reduced)
            .expect("invariant: the solution has one entry per basis generator"))
    }

    /// Whether a monzo is tempered out, that is, lies in the kernel.
    ///
    /// # Errors
    ///
    /// Returns [`TemperamentError::BasisMismatch`] if the monzo is over an
    /// unrelated basis.
    pub fn kills(&self, monzo: &Monzo) -> Result<bool, TemperamentError> {
        Ok(self.apply(monzo)?.is_zero())
    }
}

#[cfg(test)]
mod tests {
    use super::TemperamentMap;
    use crate::algebra::Z;
    use crate::error::TemperamentError;
    use crate::proportion::Basis;
    use crate::temperament::image::AmbientLattice;
    use alloc::sync::Arc;

    fn five_limit() -> Arc<Basis> {
        Basis::primes("umt:prime:2.3.5", &[2, 3, 5]).unwrap()
    }

    #[test]
    fn shape_is_validated() {
        let basis = five_limit();
        let steps = AmbientLattice::new("umt:edo:12", 1);
        assert_eq!(
            TemperamentMap::from_rows(&basis, &steps, [[12i64, 19]]).unwrap_err(),
            TemperamentError::ShapeMismatch {
                expected_rows: 1,
                expected_cols: 3,
                found_rows: 1,
                found_cols: 2,
            }
        );
    }

    #[test]
    fn kernel_membership_matches_mapping_to_zero() {
        let basis = five_limit();
        let steps = AmbientLattice::new("umt:edo:12", 1);
        let map = TemperamentMap::from_rows(&basis, &steps, [[12i64, 19, 28]]).unwrap();

        for exponents in [[-4i64, 4, -1], [-19, 12, 0], [0, 0, 0], [7, -3, -1]] {
            let monzo = basis.monzo(exponents).unwrap();
            assert_eq!(
                map.kills(&monzo).unwrap(),
                map.kernel().contains(&monzo).unwrap(),
                "kernel membership must agree with mapping to zero for {exponents:?}"
            );
        }
    }

    #[test]
    fn a_rank_two_mapping_keeps_its_image_and_kernel_apart() {
        // Meantone as a rank-2 mapping: octaves and fifths.
        let basis = five_limit();
        let ambient = AmbientLattice::new("umt:meantone-coords", 2);
        let map = TemperamentMap::from_rows(&basis, &ambient, [[1i64, 0, -4], [0, 1, 4]]).unwrap();

        assert_eq!(map.rank(), 2);
        assert!(map.is_surjective());
        assert_eq!(map.kernel().rank(), 1);
        // The kernel is exactly the syntonic comma.
        assert_eq!(
            map.kernel().basis_monzos(),
            alloc::vec![basis.monzo([4, -4, 1]).unwrap()]
        );
        assert!(map.kills(&basis.monzo([-4, 4, -1]).unwrap()).unwrap());
    }

    #[test]
    fn the_zero_mapping_has_everything_in_its_kernel() {
        let basis = five_limit();
        let ambient = AmbientLattice::new("umt:zero", 1);
        let map = TemperamentMap::from_rows(&basis, &ambient, [[0i64, 0, 0]]).unwrap();

        assert_eq!(map.rank(), 0);
        assert!(!map.is_surjective());
        assert_eq!(map.image().rank(), 0);
        assert_eq!(map.kernel().rank(), 3);
        assert!(map.kills(&basis.monzo([1, 0, 0]).unwrap()).unwrap());
    }

    #[test]
    fn foreign_monzos_are_rejected() {
        let basis = five_limit();
        let other = Basis::primes("umt:prime:2.3.7", &[2, 3, 7]).unwrap();
        let steps = AmbientLattice::new("umt:edo:12", 1);
        let map = TemperamentMap::from_rows(&basis, &steps, [[12i64, 19, 28]]).unwrap();
        assert!(matches!(
            map.apply(&other.monzo([1, 0, 0]).unwrap()),
            Err(TemperamentError::BasisMismatch { .. })
        ));
    }

    #[test]
    fn preimages_are_canonical_and_small() {
        let basis = five_limit();
        let steps = AmbientLattice::new("umt:edo:12", 1);
        let map = TemperamentMap::from_rows(&basis, &steps, [[12i64, 19, 28]]).unwrap();

        // The class of seven steps comes back as the just fifth, not as some
        // enormous other member of the same fiber.
        let seven = map.ambient().element([7i64]).unwrap();
        let lift = map.preimage(&seven).unwrap();
        assert_eq!(lift, basis.monzo([-1, 1, 0]).unwrap());
        assert_eq!(lift.exact_ratio().unwrap().to_string(), "3/2");

        // Every preimage maps back, and the choice depends only on the coset.
        for step in [-13i64, -1, 0, 5, 12, 29] {
            let target = map.ambient().element([step]).unwrap();
            let lift = map.preimage(&target).unwrap();
            assert_eq!(map.apply(&lift).unwrap(), target);

            // Shifting by a comma does not change the preimage of the class.
            let shifted = lift
                .checked_add(&basis.monzo([-4, 4, -1]).unwrap())
                .unwrap();
            assert_eq!(map.preimage(&map.apply(&shifted).unwrap()).unwrap(), lift);
        }
    }

    #[test]
    fn preimages_of_unreachable_elements_are_rejected() {
        let basis = five_limit();
        let steps = AmbientLattice::new("umt:edo:6", 1);
        let map = TemperamentMap::from_rows(&basis, &steps, [[6i64, 10, 14]]).unwrap();

        assert!(map.preimage(&steps.element([4i64]).unwrap()).is_ok());
        assert!(matches!(
            map.preimage(&steps.element([3i64]).unwrap()),
            Err(TemperamentError::NotInImage { .. })
        ));

        let foreign = AmbientLattice::new("umt:other", 1);
        assert!(matches!(
            map.preimage(&foreign.element([0i64]).unwrap()),
            Err(TemperamentError::AmbientMismatch { .. })
        ));
    }

    #[test]
    fn image_coordinates_differ_from_ambient_coordinates() {
        let basis = five_limit();
        let steps = AmbientLattice::new("umt:edo:6", 1);
        let map = TemperamentMap::from_rows(&basis, &steps, [[6i64, 10, 14]]).unwrap();

        let octave = basis.monzo([1, 0, 0]).unwrap();
        assert_eq!(map.apply(&octave).unwrap().coordinates(), &[Z::from(6)]);
        assert_eq!(
            map.apply_to_image(&octave).unwrap().coordinates(),
            &[Z::from(3)],
            "the octave is 6 ambient steps but 3 image units"
        );
    }
}
